site_name: LVASPTHW
theme:
    name: readthedocs # mkdocs ## readthedocs
site_url: http://www.bigbrosci.cn
nav:
    - LVASPTHW:
      -  About "The Hard Way": LVASPTHW/Ex_00.md
      -  Ex01 为什么写本书: LVASPTHW/Ex_01.md
      -  Ex02 学习VASP的基本要求: LVASPTHW/Ex_02.md
      -  Ex03 服务器和程序语言: LVASPTHW/Ex_03.md
      -  Ex04 VASP的输入和输出: LVASPTHW/Ex_04.md
      -  Ex05 INCAR的准备: LVASPTHW/Ex_05.md
      -  Ex06 KPOINTS的准备: LVASPTHW/Ex_06.md
      -  Ex07 POSCAR的准备: LVASPTHW/Ex_07.md
      -  Ex08 POTCAR的准备: LVASPTHW/Ex_08.md
    - Appendix: 
      -  A01: Appendix/A01.md
    - Share: 
      -  S01: Share/S01.md
    - VASP 安装: 
      -  M01: Miscellaneous/M01.md
    - Trobule Shooting: 
      -  J01: Jobs/j01.md
    - Miscellaneous: 
      -  M01: Miscellaneous/M01.md
