site_name: LVASPTHW (3rd is COMING)
theme:
    name: readthedocs
site_url: http://www.bigbrosci.cn

nav:
    - 前言: Introduction.md
    - 序言: index.md
    - LVASPTHW:
      - Chapter 1 学习的基本要求:
        - Ex1.1 硬件和软件:  LVASPTHW/Ex1.1.md
        - Ex1.2 基础知识:    LVASPTHW/Ex1.2.md
        - Ex1.3 连接服务器:  LVASPTHW/Ex1.3.md
        - Ex1.4 平台三剑客: LVASPTHW/Ex1.4.md
