site_name: LVASPTHW(3rd)
theme:
    name: readthedocs
site_url: http://www.bigbrosci.cn
nav:
    - Introduction : LVASPTHW/Introduction.md
    - Preface: LVASPTHW/index.md
    - LVASPTHW:
      - Chapter 1 学习的基本要求:
        - Ex1.1 硬件:  LVASPTHW/Ex_02.md
        - Ex1.2 软件:  LVASPTHW/Ex_02.md
        - Ex1.3 基础知识:  LVASPTHW/Ex_02.md
      - Chapter 2 开始学习的准备工作: 
        - Ex2.1 服务器和程序语言: LVASPTHW/Ex_03.md
        - Ex2.2 Linux的基本命令: LVASPTHW/Ex_09.md
        - Ex2.3 Linux的文件夹相关命令: LVASPTHW/Ex_10.md
        - Ex2.4 Linux的批量处理 for: LVASPTHW/Ex_11.md
        - Ex2.5 Linux的文本编辑:  LVASPTHW/Ex_11.md
        - Ex2.5 sed: LVASPTHW/Ex_12.md
        - Ex2.6 awk:  LVASPTHW/Ex_12.md
      - Chapter 3 VASP的输入文件: 
        - Ex3.1 VASP的输入: LVASPTHW/Ex_04.md
        - Ex3.2 INCAR的准备: LVASPTHW/Ex_05.md
        - Ex3.3 KPOINTS的准备: LVASPTHW/Ex_06.md
        - Ex3.4 POSCAR的准备: LVASPTHW/Ex_07.md
        - Ex3.5 POTCAR的准备: LVASPTHW/Ex_08.md
        - Ex3.6 for + sed + KPOINTS: LVASPTHW/Ex_13.md
        - Ex3.7 for + sed + POSCAR: LVASPTHW/Ex_14.md
      - Chapter 4 VASP任务的提交:  
        - Ex4.8 连接服务器: LVASPTHW/Ex_15.md
        - Ex4.9 提交任务: LVASPTHW/Ex_16.md
      - Chapter 5 VASP的输出: 
        - Ex5.1 VASP的输出结果1: LVASPTHW/Ex_17.md
        - Ex5.2 VASP的输出结果2: LVASPTHW/Ex_18.md
        - Ex5.3 通过关键词判断任务结束: LVASPTHW/Ex_20.md
