site_name: LVASPTHW(3rd)
theme:
    name: readthedocs
site_url: http://www.bigbrosci.cn
nav:
    - 序言: Introduction.md
    - 前言: index.md
    - LVASPTHW:
      - Chapter 1 学习的基本要求:
        - Ex1.1:  LVASPTHW/Ex_02.md
      - Chapter 2 开始学习的准备工作: 
        - Ex2.1 服务器和程序语言: LVASPTHW/Ex_03.md
        - Ex2.2 Linux的基本命令: LVASPTHW/Ex_09.md
        - Ex2.3 Linux的文件夹相关命令: LVASPTHW/Ex_10.md
        - Ex2.4 Linux的批量处理 for: LVASPTHW/Ex_11.md
        - Ex2.5 Linux的文本编辑:  LVASPTHW/Ex_11.md
        - Ex2.5 sed: LVASPTHW/Ex_12.md
        - Ex2.6 awk:  LVASPTHW/Ex_12.md
      - Chapter 3 VASP的输入文件: 
        - Ex3.1 VASP的输入: LVASPTHW/Ex_04.md
        - Ex3.2 INCAR的准备: LVASPTHW/Ex_05.md
        - Ex3.3 KPOINTS的准备: LVASPTHW/Ex_06.md
        - Ex3.4 POSCAR的准备: LVASPTHW/Ex_07.md
        - Ex3.5 POTCAR的准备: LVASPTHW/Ex_08.md
        - Ex3.6 for + sed + KPOINTS: LVASPTHW/Ex_13.md
        - Ex3.7 for + sed + POSCAR: LVASPTHW/Ex_14.md
      - Chapter 4 VASP任务的提交:  
        - Ex4.8 连接服务器: LVASPTHW/Ex_15.md
        - Ex4.9 提交任务: LVASPTHW/Ex_16.md
      - Chapter 5 VASP的输出: 
        - Ex5.1 VASP的输出结果1: LVASPTHW/Ex_17.md
        - Ex5.2 VASP的输出结果2: LVASPTHW/Ex_18.md
        - Ex5.3 通过关键词判断任务结束: LVASPTHW/Ex_20.md
      - Chapter 6 VASP中非周期性体系的计算: LVASPTHW/Ex_20.md 
      - Chapter 7 VASP中周期性体系的计算: LVASPTHW/Ex_20.md
      - Chapter 8 VASP计算材料: LVASPTHW/Ex_20.md
      - Chapter 9 VASP计算表面性质: LVASPTHW/Ex_20.md
      - Chapter 10 VASP计算表面反应: LVASPTHW/Ex_20.md
      - Chapter 20: 
        - Ex20.1 VASP5.4 :  Install/IN01.md
        - Ex20.2 通过Intel OneAPI 编译VASP5.4.4 :  Install/IN03.md
        - Ex20.3 VTST编译:      Install/IN10.md
        - Ex20.4  VASPsol:      Install/IN10.md
      - Chapter 21 Trobule Shooting: 
        - Ex21.1 自洽迭代计算框架介绍: TS/TS01.md
        - Ex21.2 自洽迭代与ISTART参数: TS/TS02.md
        - Ex21.3 自洽迭代与MIXING参数: TS/TS03.md
        - Ex21.4 常见问题及解答: QA/QA.md
        - Ex21.5 VASP遇到错误的解决流程: QA/QA10.md
    - Share/分享:
        - 博士博后位置 :  Share/J01.md
        - Python       : Share/S01.md
        - 数据库       : Share/S02.md
        - 视频教程     : Share/S02.md
        - Github       : Share/S04.md
