site_name: LVASPTHW(3rd)
theme:
    name: readthedocs
site_url: http://www.bigbrosci.cn
nav:
    - Introduction : LVASPTHW/Introduction.md
    - Preface: LVASPTHW/index.md
    - LVASPTHW:
      - Chapter 1 学习的基本要求:
        - Ex1.1 硬件:  LVASPTHW/Ex_02.md
        - Ex1.2 软件:  LVASPTHW/Ex_02.md
        - Ex1.3 基础知识:  LVASPTHW/Ex_02.md
      - Chapter 2 开始学习的准备工作: 
        - Ex2.1 服务器和程序语言: LVASPTHW/Ex_03.md
        - Ex2.2 Linux的基本命令: LVASPTHW/Ex_09.md
        - Ex2.3 Linux的文件夹相关命令: LVASPTHW/Ex_10.md
        - Ex2.4 Linux的批量处理 for: LVASPTHW/Ex_11.md
        - Ex2.5 Linux的文本编辑:  LVASPTHW/Ex_11.md
        - Ex2.5 sed: LVASPTHW/Ex_12.md
        - Ex2.6 awk:  LVASPTHW/Ex_12.md
