site_name: LVASPTHW (3rd is OTW)
theme:
    name: readthedocs
site_url: http://www.bigbrosci.cn

nav:
    - 通知: index.md
    - 前言: Introduction.md
    - 序言: 序言.md
    - LVASPTHW:
      - Chapter 1 学习的基本要求:
        - Ex1.1 硬件和软件:  LVASPTHW/Ex1.1.md
        - Ex1.2 基础知识:    LVASPTHW/Ex1.2.md
        - Ex1.3 连接服务器:  LVASPTHW/Ex1.3.md
        - Ex1.4 平台三剑客:  LVASPTHW/Ex1.4.md
        - Ex1.5 磨剑:        LVASPTHW/Ex1.5.md
        - Ex1.6 磨刀:        LVASPTHW/Ex1.6.md   
        - Ex1.7 Python IDE:  LVASPTHW/Ex1.7.md   
        - Ex1.8 基本的Linux命令:  LVASPTHW/Ex1.8.md
        - Ex1.9 Vasp的编译:  LVASPTHW/Ex1.9.md
      - Chapter 2 VASP的输入:
        - Ex2.1 基本的概念:       LVASPTHW/Ex2.1.md
        - Ex2.2 INCAR的介绍:      LVASPTHW/Ex2.2.md
        - Ex2.3 KPOINTS的准备:    LVASPTHW/Ex2.3.md
        - Ex2.4 POSCAR的准备:     LVASPTHW/Ex2.4.md
        - Ex2.5 POTCAR的介绍:     LVASPTHW/Ex2.5.md
        - Ex2.6 POTCAR的制备:     LVASPTHW/Ex2.6.md
        - Ex2.7 输入文件检查:     LVASPTHW/Ex2.7.md
        - Ex2.8 连接服务器:       LVASPTHW/Ex2.8.md
        - Ex2.9 VASP任务的提交:   LVASPTHW/Ex2.9.md
      - Chapter 3 VASP的输出:
        - Ex3.1 基本的概念:    LVASPTHW/Ex3.1.md
        - Ex3.2 CONTCAR,XDATCAR:       LVASPTHW/Ex3.2.md
        - Ex3.3 OSZICAR:       LVASPTHW/Ex3.3.md
        - Ex3.4 OUTCAR:        LVASPTHW/Ex3.4.md
        - Ex3.5 DOSCAR:        LVASPTHW/Ex3.5.md
        - Ex3.6 PROCAR:        LVASPTHW/Ex3.6.md
        - Ex3.7 Charge_Cars:   LVASPTHW/Ex3.7.md
        - Ex3.7 WAVECAR:       LVASPTHW/Ex3.8.md
      - Chapter 4 VASP任务的处理:
        - Ex3.11 判断计算结束: LVASPTHW/Ex3.11.md
        - Ex3.12 检查计算结果: LVASPTHW/Ex3.12.md
        - Ex4.1 Linux下的批量处理:    LVASPTHW/Ex4.1.md
        - Ex4.2 for + sed:            LVASPTHW/Ex4.2.md
        - Ex4.3 for + sed + KPOINTS:  LVASPTHW/Ex4.3.md
        - Ex4.4 for + sed + POSCAR:   LVASPTHW/Ex4.4.md
        - Ex4.5 VASP任务的批量提交-1: LVASPTHW/Ex4.5.md
        - Ex4.6 VASP任务的批量提交-2: LVASPTHW/Ex4.6.md
      - Chapter 5 气相体系的计算:
        - Ex5.1 单原子:    LVASPTHW/ExN.md
        - Ex5.2 双原子:    LVASPTHW/ExN.md
        - Ex5.3 三原子:    LVASPTHW/ExN.md
        - Ex5.4 多原子:    LVASPTHW/ExN.md
        - Ex5.5 热力学:    LVASPTHW/ExN.md
      - Chapter 6 体相体系的计算:
        - Ex6.1 Bulk的搭建:    LVASPTHW/ExN.md
        - Ex6.2 Bulk的优化:    LVASPTHW/ExN.md
        - Ex6.3 热力学:        LVASPTHW/ExN.md
      - Chapter 7 表面体系的计算:
        - Ex7.1 slab模型:    LVASPTHW/ExN.md
        - Ex7.9 热力学:      LVASPTHW/ExN.md
      - Chapter 8 建模进阶:
        - Ex8.1 建模软件:    LVASPTHW/ExN.md
        - Ex8.2 建模思路:    LVASPTHW/ExN.md
      - Chapter 9 VASP的特殊版本以及后处理程序:
        - Ex9.1 VTST:       LVASPTHW/ExN.md
        - Ex9.2 VASPsol++:  LVASPTHW/ExN.md
        - Ex9.3 CP-VASP:    LVASPTHW/ExN.md
        - Ex9.4 Z_fixed:    LVASPTHW/ExN.md
        - Ex9.5 Py4vasp:    LVASPTHW/ExN.md
        - Ex9.6 ASE:        LVASPTHW/ExN.md
        - Ex9.7 Pymatgen:   LVASPTHW/ExN.md
        - Ex9.8 Phonopy:    LVASPTHW/ExN.md
        - Ex9.9 Homemade:   LVASPTHW/ExN.md
      - Chapter 10 Trouble Shooting: 
        - Ex10.1 思路:       LVASPTHW/ExN.md
        - Ex10.9 ChatGpt:    LVASPTHW/ExN.md
      - Chapter 11 Misc Information: 
        - Ex11.1 数据库:       LVASPTHW/ExN.md
        - Ex11.2 超算中心:     LVASPTHW/ExN.md
        - Ex11.3 替代软件:     LVASPTHW/ExN.md
        - Ex11.4 推荐书:       LVASPTHW/ExN.md
      - Chapter 12 实用小脚本: 
        - Ex12.1 数据压缩:    LVASPTHW/Ex12.1.md
        - Ex12.2 Ubuntu字体安装:    LVASPTHW/Ex12.2.md
        - Ex12.3 Latex学习:    LVASPTHW/Ex12.3.md
