site_name: LVASPTHW
theme:
    name: readthedocs # mkdocs ## readthedocs
site_url: http://www.bigbrosci.cn
nav:
    - About: about.md
    - LVASPTHW:
      -  Ex00: LVASPTHW/Ex_00.md
      -  Ex01: LVASPTHW/Ex_01.md
      -  Ex02: LVASPTHW/Ex_02.md
      -  Ex03: LVASPTHW/Ex_03.md
      -  Ex04: LVASPTHW/Ex_04.md
      -  Ex05: LVASPTHW/Ex_05.md
    - Appendix: 
      -  A01: Appendix/A01.md
    - Share: 
      -  S01: Share/S01.md
    - Miscellaneous: 
      -  M01: Miscellaneous/M01.md
    - Jobs: 
      -  J01: Jobs/j01.md
      -  J02: Jobs/j02.md 
