site_name: LVASPTHW(3rd)
theme:
    name: readthedocs
site_url: http://www.bigbrosci.cn
nav:
    - Introduction : Introduction.md
    - Preface: index.md
    - LVASPTHW:
      - Chapter 1 学习的基本要求:
        - Ex1.1 硬件:  LVASPTHW/Ex_02.md
        - Ex1.2 软件:  LVASPTHW/Ex_02.md
        - Ex1.3 基础知识:  LVASPTHW/Ex_02.md
      - Chapter 2 开始学习的准备工作: 
        - Ex2.1 服务器和程序语言: LVASPTHW/Ex_03.md
        - Ex2.2 Linux的基本命令: LVASPTHW/Ex_09.md
        - Ex2.3 Linux的文件夹相关命令: LVASPTHW/Ex_10.md
        - Ex2.4 Linux的批量处理 for: LVASPTHW/Ex_11.md
        - Ex2.5 Linux的文本编辑:  LVASPTHW/Ex_11.md
        - Ex2.5 sed: LVASPTHW/Ex_12.md
        - Ex2.6 awk:  LVASPTHW/Ex_12.md
      - Chapter 3 VASP的输入文件: 
        - Ex3.1 VASP的输入: LVASPTHW/Ex_04.md
        - Ex3.2 INCAR的准备: LVASPTHW/Ex_05.md
        - Ex3.3 KPOINTS的准备: LVASPTHW/Ex_06.md
        - Ex3.4 POSCAR的准备: LVASPTHW/Ex_07.md
        - Ex3.5 POTCAR的准备: LVASPTHW/Ex_08.md
        - Ex3.6 for + sed + KPOINTS: LVASPTHW/Ex_13.md
        - Ex3.7 for + sed + POSCAR: LVASPTHW/Ex_14.md
      - Chapter 4 VASP任务的提交:  
        - Ex4.8 连接服务器: LVASPTHW/Ex_15.md
        - Ex4.9 提交任务: LVASPTHW/Ex_16.md
      - Chapter 5 VASP的输出: 
        - Ex5.1 VASP的输出结果1: LVASPTHW/Ex_17.md
        - Ex5.2 VASP的输出结果2: LVASPTHW/Ex_18.md
        - Ex5.3 通过关键词判断任务结束: LVASPTHW/Ex_20.md
      - Chapter 6 VASP中非周期性体系的计算:  
        - Ex6.1 VASP计算单个原子: LVASPTHW/Ex_17.md
        - Ex6.2 VASP计算双原子分子 O2 N2: LVASPTHW/Ex_17.md
        - Ex6.3 VASP计算其他分子 NH3 乙醇，甲烷: LVASPTHW/Ex_17.md
        - Ex6.4 VASP中的热力学: LVASPTHW/Ex_17.md
      - Chapter 7 VASP中周期性体系的计算: 
        - Ex7.1 VASP优化金属bulk: LVASPTHW/Ex_17.md
        - Ex7.2 VASP优化金属氧化物bulk: LVASPTHW/Ex_17.md
        - Ex7.2 VASP优化Spinel bulk DFTU: LVASPTHW/Ex_17.md
      - Chapter 8 VASP计算材料性质: 
        - Ex8.1 性质计算: LVASPTHW/Ex_17.md
      - Chapter 9 VASP计算表面性质:
        - Ex9.1 性质计算: LVASPTHW/Ex_17.md
      - Chapter 10 VASP计算热催化: 
        - Ex10.1 性质计算: LVASPTHW/Ex_17.md
      - Chapter 11 VASP计算电催化:
        - Ex11.1 性质计算: LVASPTHW/Ex_17.md
      - Chapter 12 VASP计算光催化:
        - Ex12.1 性质计算: LVASPTHW/Ex_17.md
      - Chapter 20: 
        - Ex20.1 VASP5.4 :  LVASPTHW/IN01.md
        - Ex20.2 通过Intel OneAPI 编译VASP5.4.4 :  LVASPTHW/IN03.md
        - Ex20.3 VTST编译:      LVASPTHW/IN10.md
        - Ex20.4 VASPsol:      LVASPTHW/IN10.md
      - Chapter 21 Trobule Shooting: 
        - Ex21.4 常见问题及解答: LVASPTHW/QA.md
        - Ex21.5 VASP遇到错误的解决流程: LVASPTHW/QA10.md
      - Chapter 22 寻找大师兄: 
        - Ex22 寻找大师兄: LVASPTHW/Misc.md 
