site_name: LVASPTHW(3rd)
theme:
    name: readthedocs
site_url: http://www.bigbrosci.cn
nav:
    - Introduction : LVASPTHW/Introduction.md
    - Preface: LVASPTHW/index.md
      - Chapter 1 学习的基本要求:
        - Ex1.1 硬件和软件:  LVASPTHW/Ex1.1.md
        - Ex1.2 基础知识:    LVASPTHW/Ex1.2.md
        - Ex1.3 连接服务器:  LVASPTHW/Ex1.3.md
        - Ex1.4 平台三剑客:  LVASPTHW/Ex1.4.md
        - Ex1.5 磨剑:  LVASPTHW/Ex1.5.md
        - Ex1.6 磨刀:  LVASPTHW/Ex1.6.md
        - Ex1.7 Vasp的编译:  LVASPTHW/Ex1.7.md
      - Chapter 2 VASP的输入:
        - Ex2.1 基本的概念:       LVASPTHW/Ex2.1.md
        - Ex2.2 INCAR的准备:      LVASPTHW/Ex2.2.md
        - Ex2.3 KPOINTS的准备:    LVASPTHW/Ex2.3.md
        - Ex2.4 POSCAR的准备:     LVASPTHW/Ex2.4.md
        - Ex2.5 POTCAR的准备:     LVASPTHW/Ex2.5.md
        - Ex2.6 输入文件检查:     LVASPTHW/Ex2.5.md
        - Ex2.7 基本的Linux命令:  LVASPTHW/Ex2.5.md
        - Ex2.8 连接服务器:       LVASPTHW/Ex2.5.md
        - Ex2.9 VASP任务的提交:   LVASPTHW/Ex2.5.md
      - Chapter 3 VASP的输出:
        - Ex3.1 基本的概念:    LVASPTHW/Ex3.1.md
        - Ex3.2 CONTCAR:       LVASPTHW/Ex3.2.md
        - Ex3.3 OSZICAR:       LVASPTHW/Ex3.3.md
        - Ex3.4 OUTCAR:        LVASPTHW/Ex3.4.md
        - Ex3.5 DOSCAR:        LVASPTHW/Ex3.5.md
        - Ex3.6 PROCAR:        LVASPTHW/Ex3.6.md
        - Ex3.7 XDATCAR:       LVASPTHW/Ex3.7.md
        - Ex3.8 CHG,CHGCAR:    LVASPTHW/Ex3.8.md
        - Ex3.9 WAVECAR:       LVASPTHW/Ex3.9.md
        - Ex3.10 vasprun.xml:  LVASPTHW/Ex3.10.md
        - Ex3.11 判断计算结束: LVASPTHW/Ex3.11.md
        - Ex3.12 检查计算结果: LVASPTHW/Ex3.12.md
      - Chapter 4 VASP任务的批量处理:
        - Ex4.1 Linux下的批量处理:    LVASPTHW/Ex4.1.md
        - Ex4.2 for + sed:            LVASPTHW/Ex4.2.md
        - Ex4.3 for + sed + KPOINTS:  LVASPTHW/Ex4.3.md
        - Ex4.4 for + sed + POSCAR:   LVASPTHW/Ex4.4.md
        - Ex4.5 VASP任务的批量提交-1: LVASPTHW/Ex4.5.md
        - Ex4.6 VASP任务的批量提交-2: LVASPTHW/Ex4.6.md
      - Chapter 5 VASP中非周期性体系的计算:  
        - Ex5.1 VASP计算单个原子: LVASPTHW/Ex_17.md
        - Ex5.2 VASP计算双原子分子 O2 N2: LVASPTHW/Ex_17.md
        - Ex5.3 VASP计算其他分子 NH3 乙醇，甲烷: LVASPTHW/Ex_17.md
        - Ex5.4 VASP中的热力学: LVASPTHW/Ex_17.md
      - Chapter 6 VASP中周期性体系的计算: 
        - Ex6.1 VASP优化金属bulk: LVASPTHW/Ex_17.md
        - Ex6.2 VASP优化金属氧化物bulk: LVASPTHW/Ex_17.md
        - Ex6.2 VASP优化Spinel bulk DFTU: LVASPTHW/Ex_17.md
      - Chapter 7 VASP 中的热力学
        - Ex7.1 非周期性体系的热力学: LVASPTHW/Ex_17.md
        - Ex7.2 周期性体系的热力学: LVASPTHW/Ex_17.md
      - Chapter 8 VASP计算材料性质: 
        - Ex8.1 性质计算: LVASPTHW/Ex_17.md
      - Chapter 9 VASP计算表面性质:
        - Ex9.1 性质计算: LVASPTHW/Ex_17.md
      - Chapter 10 VASP计算热催化: 
        - Ex10.1 性质计算: LVASPTHW/Ex_17.md
      - Chapter 11 VASP计算电催化:
        - Ex11.1 性质计算: LVASPTHW/Ex_17.md
      - Chapter 12 VASP计算光催化:
        - Ex12.1 性质计算: LVASPTHW/Ex_17.md
      - Chapter 20: 
        - Ex20.1 VASP5.4 :  Install/IN01.md
        - Ex20.2 通过Intel OneAPI 编译VASP5.4.4 :  Install/IN03.md
        - Ex20.3 VTST编译:      Install/IN10.md
        - Ex20.4 VASPsol:      Install/IN10.md
      - Chapter 21 Trobule Shooting: 
        - Ex21.1 自洽迭代计算框架介绍: TS/TS01.md
        - Ex21.2 自洽迭代与ISTART参数: TS/TS02.md
        - Ex21.3 自洽迭代与MIXING参数: TS/TS03.md
        - Ex21.4 常见问题及解答: QA/QA.md
        - Ex21.5 VASP遇到错误的解决流程: QA/QA10.md
      - Chapter 22 寻找大师兄: 
        - Ex22 寻找大师兄: LVASPTHW/Misc.md 
    - Share/分享:
        - 博士博后位置 : Share/J01.md
        - Python       : Share/S01.md
        - 数据库       : Share/S02.md
        - 视频教程     : Share/S02.md
        - Github       : Share/S04.md
